import React, {useMemo, useState} from 'react';
import {ArrowRight, Check, ChevronRight, Clock3, Minus, Plus, Search, ShieldCheck, ShoppingBag, Sparkles, Store, Truck, X, Zap} from 'lucide-react';
import {createRoot} from 'react-dom/client';
import './styles.css';

type Product={id:number;name:string;category:string;price:number;stock:number;emoji:string;description:string};
type Mart={id:number;name:string;area:string;distance:string;eta:string;initials:string;accent:string};
type Cart=Record<number,number>;
type DeliveryMode='express'|'clubbed';

const marts:Mart[]=[
 {id:1,name:'Shree Ganesh Kirana',area:'Viman Nagar',distance:'0.8 km away',eta:'7–10 min',initials:'SG',accent:'mint'},
 {id:2,name:'Om Sai General Store',area:'Kalyani Nagar',distance:'1.4 km away',eta:'10–14 min',initials:'OS',accent:'sun'},
 {id:3,name:'Laxmi Provision Mart',area:'Yerawada',distance:'2.1 km away',eta:'12–16 min',initials:'LP',accent:'rose'},
 {id:4,name:'Mahalaxmi Kirana',area:'Aundh Road',distance:'2.7 km away',eta:'15–18 min',initials:'MK',accent:'blue'}
];
const products:Product[]=[
 {id:1,name:'Jowar Flour 1kg',category:'Staples',price:78,stock:18,emoji:'🌾',description:'Stone-ground bhakri flour'},
 {id:2,name:'Sharbati Wheat 5kg',category:'Staples',price:285,stock:9,emoji:'🌾',description:'Daily atta for soft rotis'},
 {id:3,name:'Toor Dal 1kg',category:'Pulses',price:168,stock:14,emoji:'🫘',description:'Unpolished pigeon peas'},
 {id:4,name:'Kolam Rice 5kg',category:'Staples',price:395,stock:8,emoji:'🍚',description:'Everyday steamed rice'},
 {id:5,name:'Sunflower Oil 1L',category:'Cooking',price:142,stock:16,emoji:'🫗',description:'Light everyday cooking oil'},
 {id:6,name:'Jaggery Powder 500g',category:'Staples',price:62,stock:21,emoji:'🟤',description:'Naturally sweet unrefined gud'},
 {id:7,name:'Chilli Powder 200g',category:'Spices',price:74,stock:11,emoji:'🌶️',description:'Bright, earthy Byadgi chilli'},
 {id:8,name:'Tata Salt 1kg',category:'Essentials',price:28,stock:30,emoji:'🧂',description:'Iodised cooking salt'},
 {id:9,name:'Fresh Curd 500g',category:'Dairy',price:45,stock:12,emoji:'🥣',description:'Set this morning nearby'},
 {id:10,name:'Masala Tea 250g',category:'Beverages',price:105,stock:13,emoji:'🍵',description:'Strong chai blend'},
 {id:11,name:'Poha 1kg',category:'Staples',price:86,stock:10,emoji:'🌽',description:'Thick flattened rice'},
 {id:12,name:'Coconut Soap 4 pack',category:'Essentials',price:132,stock:7,emoji:'🧼',description:'Gentle daily bath soap'}
];
const money=(n:number)=>`₹${n.toFixed(2)}`;
const categories=['All','Staples','Pulses','Cooking','Spices','Essentials','Dairy','Beverages'];

function App(){
 const [screen,setScreen]=useState<'login'|'shop'>('login'); const [phone,setPhone]=useState('+91 98765 43210');
 const [cart,setCart]=useState<Cart>({}); const [query,setQuery]=useState(''); const [category,setCategory]=useState('All'); const [selectedMart,setSelectedMart]=useState(1); const [drawer,setDrawer]=useState(false); const [checkout,setCheckout]=useState(false); const [delivery,setDelivery]=useState<DeliveryMode>('express'); const [state,setState]=useState<'idle'|'processing'|'success'>('idle'); const [order,setOrder]=useState('');
 const filtered=useMemo(()=>products.filter(p=>(category==='All'||p.category===category)&&p.name.toLowerCase().includes(query.toLowerCase())),[query,category]);
 const count=Object.values(cart).reduce((a,b)=>a+b,0); const total=Object.entries(cart).reduce((s,[id,q])=>s+products.find(p=>p.id===+id)!.price*q,0); const mart=marts.find(x=>x.id===selectedMart)!;
 const add=(p:Product)=>setCart(c=>({...c,[p.id]:Math.min(10,(c[p.id]||0)+1)}));
 const remove=(p:Product)=>setCart(c=>{const n={...c}; if((n[p.id]||0)<=1)delete n[p.id]; else n[p.id]--; return n});
 const place=()=>{setState('processing');setTimeout(()=>{setState('success');setOrder('KM-'+Math.random().toString(36).slice(2,8).toUpperCase());setCart({})},700)};
 if(screen==='login') return <Login phone={phone} setPhone={setPhone} onContinue={()=>setScreen('shop')}/>;
 return <div className="app"><header className="nav"><div className="brand"><span className="brandmark"><Store size={17}/></span><span>Kirana<span>Connect</span></span></div><div className="navsearch"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search atta, dal, masala..."/></div><div className="navright"><button className="location"><span className="dot"/>Delivering to <b>Viman Nagar</b></button><button className="cartbtn" onClick={()=>setDrawer(true)}><ShoppingBag size={18}/><span>Cart</span>{count>0&&<i>{count}</i>}</button><button className="avatar" onClick={()=>setScreen('login')}>A</button></div></header>
 <main><section className="hero"><div><p className="eyebrow"><Sparkles size={14}/> Your neighbourhood, delivered</p><h1>Ghar ka samaan.<br/><em>Apne kirana se.</em></h1><p className="heroCopy">Shop staples and daily essentials from trusted local kirana marts. Every order supports the store around your corner.</p><div className="heroStats"><span><Clock3 size={16}/><b>7–10 min</b> express delivery</span><span><ShieldCheck size={16}/><b>Fresh</b> from local shelves</span></div></div><div className="deliveryCard"><div className="radar"><div className="ring r1"/><div className="ring r2"/><div className="pin"><Store size={23}/></div></div><div><b>{mart.name}</b><p>{mart.distance} · open now</p></div><span className="live">OPEN</span></div></section>
 <section className="martSection"><div className="sectionHead"><div><p className="eyebrow">LOCAL KIRANA MARTS</p><h2>Pick your nearby store</h2></div><span>4 stores near you</span></div><div className="martGrid">{marts.map(m=><button key={m.id} className={`martCard ${selectedMart===m.id?'selected':''}`} onClick={()=>setSelectedMart(m.id)}><span className={`martAvatar ${m.accent}`}>{m.initials}</span><span className="martInfo"><b>{m.name}</b><small>{m.area} · {m.distance}</small></span><span className="martEta"><strong>{m.eta}</strong><small>delivery</small></span></button>)}</div></section>
 <section className="categories">{categories.map(c=><button className={category===c?'active':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</section>
 <section className="sectionHead productsHead"><div><p className="eyebrow">AVAILABLE AT {mart.name.toUpperCase()}</p><h2>Staples for every kitchen</h2></div><span>{filtered.length} products</span></section>
 <div className="grid">{filtered.map(p=><ProductCard key={p.id} p={p} qty={cart[p.id]||0} add={add} remove={remove}/>)}</div></main>
 {drawer&&<CartDrawer cart={cart} total={total} mart={mart} remove={remove} add={add} close={()=>setDrawer(false)} checkout={()=>{setDrawer(false);setCheckout(true);setState('idle')}}/>}
 {checkout&&<Checkout cart={cart} total={total} mart={mart} delivery={delivery} setDelivery={setDelivery} state={state} order={order} place={place} close={()=>setCheckout(false)} edit={()=>{setCheckout(false);setDrawer(true)}}/>}<div className="api-pill"><span/> Local stores · real-time availability</div></div>
}

function Login({phone,setPhone,onContinue}:{phone:string;setPhone:(v:string)=>void;onContinue:()=>void}){return <div className="loginPage"><div className="loginVisual"><div className="loginLogo"><span><Store size={20}/></span> KiranaConnect</div><div className="visualCopy"><p className="eyebrow"><Zap size={14}/> LOCAL SHOPPING, MADE EASY</p><h1>Your local kirana.<br/><em>At your door.</em></h1><p>Bring the familiar neighbourhood store to your phone. Buy the staples you trust, delivered when you need them.</p><div className="miniFlow"><div><b>01</b><span>Choose a mart</span></div><ArrowRight/><div><b>02</b><span>Fill your basket</span></div><ArrowRight/><div><b>03</b><span>Get it home</span></div></div></div><div className="loginFoot">Supporting local kirana owners · Serving Viman Nagar</div></div><div className="loginPanel"><div className="mobileBrand"><span><Store size={18}/></span> KiranaConnect</div><div className="loginBox"><div className="stepBadge">01 / GET STARTED</div><h2>Namaste.</h2><p>Enter your phone number to shop from local kirana marts.</p><label>Phone number</label><div className="phoneInput"><span>🇮🇳 +91</span><input value={phone.replace('+91 ','')} onChange={e=>setPhone('+91 '+e.target.value)} placeholder="98765 43210"/></div><button className="primary full" onClick={onContinue}>Start shopping <ArrowRight size={18}/></button><p className="fine">Demo login: any valid phone format continues.</p></div></div></div>}
function ProductCard({p,qty,add,remove}:{p:Product;qty:number;add:(p:Product)=>void;remove:(p:Product)=>void}){return <article className="product"><div className="productVisual"><span>{p.emoji}</span></div><div className="productBody"><div className="meta"><span>{p.category}</span><small>{p.stock} left</small></div><h3>{p.name}</h3><p>{p.description}</p><div className="productBottom"><strong>{money(p.price)}</strong>{qty===0?<button className="add" onClick={()=>add(p)}>Add <Plus size={15}/></button>:<div className="stepper"><button onClick={()=>remove(p)}><Minus size={14}/></button><b>{qty}</b><button onClick={()=>add(p)}><Plus size={14}/></button></div>}</div></div></article>}
function CartDrawer({cart,total,mart,remove,add,close,checkout}:{cart:Cart;total:number;mart:Mart;remove:(p:Product)=>void;add:(p:Product)=>void;close:()=>void;checkout:()=>void}){return <div className="overlay" onClick={close}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawerHead"><div><p className="eyebrow">YOUR BASKET · {mart.name}</p><h2>{Object.values(cart).reduce((a,b)=>a+b,0)} items</h2></div><button className="iconBtn" onClick={close}><X/></button></div><div className="drawerItems">{Object.keys(cart).length===0?<div className="empty"><ShoppingBag size={35}/><h3>Your basket is empty</h3><p>Add staples from your local mart to get started.</p></div>:Object.entries(cart).map(([id,q])=>{const p=products.find(x=>x.id===+id)!;return <div className="cartLine" key={id}><span className="cartEmoji">{p.emoji}</span><div className="lineInfo"><b>{p.name}</b><small>{money(p.price)} each</small><div className="miniStepper"><button onClick={()=>remove(p)}><Minus size={12}/></button><b>{q}</b><button onClick={()=>add(p)}><Plus size={12}/></button></div></div><strong>{money(p.price*q)}</strong></div>})}</div><div className="drawerFoot"><div className="subtotal"><span>Subtotal</span><b>{money(total)}</b></div><p><Truck size={14}/> Delivery fee <b>FREE</b></p><button className="primary full" disabled={!total} onClick={checkout}>Choose delivery <ChevronRight size={18}/></button></div></aside></div>}
function Checkout({cart,total,mart,delivery,setDelivery,state,order,place,close,edit}:{cart:Cart;total:number;mart:Mart;delivery:DeliveryMode;setDelivery:(v:DeliveryMode)=>void;state:string;order:string;place:()=>void;close:()=>void;edit:()=>void}){const eta=delivery==='express'?'7–10 minutes':'20–30 minutes'; return <div className="overlay"><div className="checkout"><div className="checkoutHead"><div><p className="eyebrow">CHECKOUT</p><h2>Bring it home</h2></div><button className="iconBtn" onClick={close}><X/></button></div>{state==='success'?<div className="success"><div className="successIcon"><Check size={32}/></div><p className="eyebrow">ORDER CONFIRMED</p><h2>Dhanyavaad.</h2><p>Order <b>{order}</b> is on its way from <b>{mart.name}</b>.</p><div className="successRow"><span>Delivery</span><b>{delivery==='express'?'Express':'Clubbed'} · {eta}</b></div><div className="successRow"><span>Payment</span><b>Pay on delivery</b></div><button className="primary full" onClick={close}>Continue shopping</button></div>:<><div className="checkoutFlow"><span className="done"><Check size={13}/> Basket</span><ChevronRight/><span className="current">Delivery</span><ChevronRight/><span>Confirmed</span></div><div className="storeNotice"><Store size={18}/><span><b>{mart.name}</b><small>{mart.area} · your order is packed locally</small></span></div><div className="deliveryOptions"><button className={delivery==='express'?'deliveryOption chosen':'deliveryOption'} onClick={()=>setDelivery('express')}><span className="optionIcon express"><Zap size={17}/></span><span><b>Express delivery</b><small>Delivered in 7–10 minutes</small></span><i>{delivery==='express'&&<Check size={15}/>}</i></button><button className={delivery==='clubbed'?'deliveryOption chosen':'deliveryOption'} onClick={()=>setDelivery('clubbed')}><span className="optionIcon clubbed"><Truck size={17}/></span><span><b>Clubbed delivery</b><small>20–30 min · save rider trips and ₹10</small></span><i>{delivery==='clubbed'&&<Check size={15}/>}</i></button></div><div className="reviewLines">{Object.entries(cart).map(([id,q])=>{const p=products.find(x=>x.id===+id)!;return <div key={id}><span>{q} × {p.name}</span><b>{money(p.price*q)}</b></div>})}</div><div className="priceBox"><span>Subtotal</span><b>{money(total)}</b><span>Delivery</span><b className="free">FREE</b>{delivery==='clubbed'&&<><span>Clubbed saving</span><b className="free">−₹10.00</b></>}<hr/><strong>Total</strong><strong>{money(Math.max(0,total-(delivery==='clubbed'?10:0)))}</strong></div><div className="checkoutActions"><button className="secondary" onClick={edit}>Edit basket</button><button className="primary" onClick={place} disabled={state==='processing'}>{state==='processing'?'Placing order...':<>Place order <ArrowRight size={16}/></>}</button></div></>}</div></div>}

createRoot(document.getElementById('root')!).render(<App/>);
